// UI string registry — the single source of truth for editable customer- AND admin-facing wording
// (BETA item 9, the Language editor). KEYS + DEFAULTS live here (versioned with the code); admin edits
// are stored as SPARSE overrides in the `ui_strings` table. Resolution is `override ?? default`, so an
// unedited string always renders its built-in default, a missing row never breaks anything, and deleting
// a row IS "reset to default".
//
// To make a new string editable: add a key here (with a plain-English `desc` + a `group` for the admin
// Language page) and call t('that.key') where it renders. Nothing else to wire.

export type UiStringDef = { default: string; group: string; desc: string }

export const UI_STRINGS = {
  // ── Brand ──────────────────────────────────────────────────────────────────
  // The app / design-tool name. A single editable string so an eventual rename is one edit
  // (the tool is slated to be renamed, name TBD).
  'app.name': { default: 'TEE STUDIO', group: 'Brand', desc: 'The design tool / app name shown in headers (e.g. the order page).' },
  // ── Methods ────────────────────────────────────────────────────────────────
  // The internal DB keys (screen_print / embroidery) NEVER change; this is DISPLAY only. "Print" is the
  // default so "Screen Print" / "silk screen" can't come back (BETA #15).
  'method.screen_print': { default: 'Print', group: 'Methods', desc: 'Name shown for the print method (customer + admin). Internal key stays "screen_print".' },
  'method.embroidery': { default: 'Embroidery', group: 'Methods', desc: 'Name shown for the embroidery method (customer + admin).' },

  // ── Order page ───────────────────────────────────────────────────────────────
  'order.blank_line': { default: 'Blank product', group: 'Order page', desc: 'Label for the blank-garment line in the order summary (sometimes a hat, not a shirt — BETA #16).' },
  // Desired-by date (BETA #30) — optional; turnaround copy is method-aware.
  'order.desired_by_label': { default: 'Desired by', group: 'Order page', desc: 'Label for the optional "desired by" date picker on the order page (BETA #30).' },
  'order.desired_by_help_print': { default: 'Typical turnaround: print 24–72 hours.', group: 'Order page', desc: 'Turnaround expectation shown beside the Desired-by date for PRINT orders (BETA #30).' },
  'order.desired_by_help_embroidery': { default: 'Typical turnaround: embroidery about a week.', group: 'Order page', desc: 'Turnaround expectation shown beside the Desired-by date for EMBROIDERY orders (BETA #30).' },
  'order.desired_by_nudge': { default: "That's sooner than our usual turnaround — we'll do our best, but please call us to confirm.", group: 'Order page', desc: 'Soft nudge (never blocks) shown when the chosen desired-by date is sooner than turnaround (BETA #30).' },

  // ── Notifications / confirms ─────────────────────────────────────────────────
  'notify.clear_all_confirm': { default: 'Clear all design elements?', group: 'Notifications', desc: 'Confirmation shown before clearing the whole design (BETA #19, wording).' },

  // ── Admin — Art library ──────────────────────────────────────────────────────
  'admin.design_number': { default: 'Design #', group: 'Admin — Art', desc: 'Label for an art item’s design number in the Art admin (was "Decal #" — BETA #22).' },
  'admin.designs_used': { default: 'Designs Used', group: 'Admin — Orders', desc: 'Heading over the list of design numbers used on an order (was "Decals Used").' },
  'admin.desired_by_label': { default: 'Desired by', group: 'Admin — Orders', desc: 'Label for the customer-requested "desired by" date shown on an order in admin (BETA #30).' },
  'admin.design_notes_heading': { default: 'Design Notes', group: 'Admin — Orders', desc: 'Heading over the customer design-notes on an order in admin.' },

  // ── Designer (customer) — a starter set of the most-visible labels/notes ─────
  'designer.embroidery_preview_note': { default: 'Preview — final stitching may vary.', group: 'Designer', desc: 'Honesty note shown in embroidery mode next to the design.' },

  // ── Designer — Text ──
  'designer.text.your_text_label': { default: "Your Text", group: "Designer — Text", desc: "Label above the text-entry box in the designer's Text panel." },
  'designer.text.placeholder': { default: "Type something...\nPress Enter for a new line", group: "Designer — Text", desc: "Placeholder shown inside the empty text-entry box (two lines)." },
  'designer.text.edit_hint_prefix': { default: "Or ", group: "Designer — Text", desc: "First part of the hint telling customers how else to edit text on the shirt (precedes the bold 'double-click')." },
  'designer.text.edit_hint_action': { default: "double-click", group: "Designer — Text", desc: "The emphasized action word in the edit-text hint ('double-click')." },
  'designer.text.edit_hint_suffix': { default: " the text on the shirt to edit it here.", group: "Designer — Text", desc: "Remainder of the edit-text hint after the bold 'double-click'." },
  'designer.text.add_another': { default: "+ Add another text", group: "Designer — Text", desc: "Button to start a brand-new text object when one is already selected." },
  'designer.text.font_label': { default: "Font", group: "Designer — Text", desc: "Label above the font picker in the Text panel." },
  'designer.text.preview_placeholder': { default: "Preview Text", group: "Designer — Text", desc: "Sample text shown in the font-picker preview when the customer hasn't typed anything yet." },
  'designer.text.size_label': { default: "Size", group: "Designer — Text", desc: "Label for the text font-size control." },
  'designer.text.letter_spacing_label': { default: "Letter Spacing", group: "Designer — Text", desc: "Label for the letter-spacing (tracking) slider." },
  'designer.text.line_spacing_label': { default: "Line Spacing", group: "Designer — Text", desc: "Label for the line-spacing slider (multi-line text only)." },
  'designer.text.curve_label': { default: "Curve", group: "Designer — Text", desc: "Label for the text-curve (arc) control." },
  'designer.text.straight': { default: "Straight", group: "Designer — Text", desc: "Button that resets curved text back to straight (curve = 0)." },
  'designer.text.curve_single_line': { default: "Curve works on single-line text.", group: "Designer — Text", desc: "Note shown when curve is unavailable because the text has multiple lines." },
  'designer.text.curve_down': { default: "⌣ Down", group: "Designer — Text", desc: "Marker at the negative end of the curve slider (arc bends downward)." },
  'designer.text.curve_up': { default: "⌢ Up", group: "Designer — Text", desc: "Marker at the positive end of the curve slider (arc bends upward)." },
  'designer.text.format_label': { default: "Format", group: "Designer — Text", desc: "Label above the bold/italic/uppercase and alignment button toolbar." },
  'designer.text.bold_tooltip': { default: "Bold", group: "Designer — Text", desc: "Tooltip for the bold text button." },
  'designer.text.italic_tooltip': { default: "Italic", group: "Designer — Text", desc: "Tooltip for the italic text button." },
  'designer.text.uppercase_tooltip': { default: "UPPERCASE", group: "Designer — Text", desc: "Tooltip for the make-uppercase text button." },
  'designer.text.align_tooltip_prefix': { default: "Align", group: "Designer — Text", desc: "Prefix of the alignment-button tooltips (followed by left/center/right/justify)." },
  'designer.text.curved_note': { default: "Curved text: straighten to change case, direction, or alignment.", group: "Designer — Text", desc: "Note explaining that case, direction, and alignment don't apply to curved text until straightened." },
  'designer.text.direction_label': { default: "Direction", group: "Designer — Text", desc: "Label above the horizontal/vertical text direction buttons." },
  'designer.text.direction_horizontal': { default: "Horizontal", group: "Designer — Text", desc: "Button for horizontal text direction." },
  'designer.text.direction_vertical': { default: "Vertical", group: "Designer — Text", desc: "Button for vertical (stacked) text direction." },
  'designer.text.color_label': { default: "Text Color", group: "Designer — Text", desc: "Label above the text-color swatch picker." },
  'designer.text.color_custom': { default: "Custom", group: "Designer — Text", desc: "Fallback name shown for the chosen text color when it doesn't match a named palette color." },
  'designer.text.sub_type': { default: "Type", group: "Designer — Text", desc: "Label for the 'Type' sub-tool tab in the mobile text controls, where the customer enters their text." },
  'designer.text.sub_font': { default: "Font", group: "Designer — Text", desc: "Label for the 'Font' sub-tool tab in the mobile text controls." },
  'designer.text.sub_size': { default: "Size", group: "Designer — Text", desc: "Label for the 'Size' sub-tool tab in the mobile text controls." },
  'designer.text.sub_color': { default: "Color", group: "Designer — Text", desc: "Label for the 'Color' sub-tool tab in the mobile text controls." },
  'designer.text.sub_style': { default: "Style", group: "Designer — Text", desc: "Label for the 'Style' sub-tool tab in the mobile text controls." },
  'designer.text.font_sample': { default: "Abc", group: "Designer — Text", desc: "Sample text shown in each font preview tile when the customer has not typed any text yet." },
  'designer.text.type_placeholder': { default: "Type something…  ↵ for a new line", group: "Designer — Text", desc: "Placeholder text inside the mobile text-entry box telling the customer to type and press Enter for a new line." },
  'designer.text.category_all': { default: "All", group: "Designer — Text", desc: "The font category chip labeled 'All' shown above the font search box." },
  'designer.text.search_fonts': { default: "Search fonts", group: "Designer — Text", desc: "Placeholder text in the font search box." },
  'designer.text.no_fonts_match': { default: "No fonts match", group: "Designer — Text", desc: "Empty-state message shown (followed by the search term) when no fonts match the font search." },
  'designer.text.custom_color': { default: "Custom color", group: "Designer — Text", desc: "Tooltip on the custom color-picker swatch for text." },
  'designer.text.align_prefix': { default: "Align", group: "Designer — Text", desc: "First word of the paragraph-alignment button tooltips (e.g. 'Align left'); the direction word follows." },
  'designer.text.bold': { default: "B", group: "Designer — Text", desc: "Label on the Bold toggle button for text." },
  'designer.text.italic': { default: "I", group: "Designer — Text", desc: "Label on the Italic toggle button for text." },
  'designer.text.uppercase': { default: "AA", group: "Designer — Text", desc: "Label on the UPPERCASE toggle button for text." },
  'designer.text.curve_singleline': { default: "Curve works on single-line text.", group: "Designer — Text", desc: "Hint shown when text has multiple lines explaining the curve control only works on single-line text." },

  // ── Designer — General ──
  'designer.delete_selected': { default: "Delete Selected", group: "Designer — General", desc: "Button that deletes the currently selected object (text, image, or clipart) from the shirt." },
  'designer.align.left': { default: "Align left", group: "Designer — General", desc: "Tooltip for the button that aligns the selected object to the left of the print area." },
  'designer.align.center': { default: "Align center", group: "Designer — General", desc: "Tooltip for the button that centers the selected object horizontally in the print area." },
  'designer.align.right': { default: "Align right", group: "Designer — General", desc: "Tooltip for the button that aligns the selected object to the right of the print area." },
  'designer.align.top': { default: "Align top", group: "Designer — General", desc: "Tooltip for the button that aligns the selected object to the top of the print area." },
  'designer.align.middle': { default: "Align middle", group: "Designer — General", desc: "Tooltip for the button that centers the selected object vertically in the print area." },
  'designer.align.bottom': { default: "Align bottom", group: "Designer — General", desc: "Tooltip for the button that aligns the selected object to the bottom of the print area." },
  'designer.align.delete': { default: "Delete", group: "Designer — General", desc: "Button that deletes the currently selected object from the shirt." },
  'designer.designs.untitled': { default: "Untitled design", group: "Designer — General", desc: "Fallback name shown for a saved design that has no name or product title." },
  'designer.designs.heading': { default: "My Designs", group: "Designer — General", desc: "Header title of the My Designs slide-over drawer." },
  'designer.designs.close': { default: "Close", group: "Designer — General", desc: "Accessible label for the ✕ button that closes the My Designs drawer." },
  'designer.designs.loading': { default: "Loading…", group: "Designer — General", desc: "Shown while the customer's saved designs are loading in the My Designs drawer." },
  'designer.designs.empty_title': { default: "No saved designs yet", group: "Designer — General", desc: "Empty-state title in the My Designs drawer when the customer has saved nothing." },
  'designer.designs.empty_hint_pre': { default: "Click", group: "Designer — General", desc: "First word of the My Designs empty-state hint, before the highlighted 'Save design' phrase." },
  'designer.designs.empty_save_word': { default: "Save design", group: "Designer — General", desc: "The highlighted button name inside the My Designs empty-state hint sentence." },
  'designer.designs.empty_hint_post': { default: "while you work and it’ll show up here to pick back up any time.", group: "Designer — General", desc: "Trailing sentence of the My Designs empty-state hint, after the 'Save design' phrase." },
  'designer.designs.open': { default: "Open", group: "Designer — General", desc: "Hover label and tooltip verb for opening a saved design tile in the My Designs drawer." },
  'designer.designs.use_tooltip': { default: "Use this design on another product", group: "Designer — General", desc: "Tooltip on the 'Use on another product' control of a saved-design tile." },
  'designer.designs.use_button': { default: "↪ Use on another product", group: "Designer — General", desc: "Button on a saved-design tile that reopens the design onto a different product." },
  'designer.designs.remove_tooltip': { default: "Remove from My Designs", group: "Designer — General", desc: "Tooltip on the ✕ button that removes a design from the My Designs library." },
  'designer.layers_heading': { default: "Layers", group: "Designer — General", desc: "Heading of the Layers panel." },
  'designer.layers_empty': { default: "Nothing on this side yet. Add text or art and it shows up here.", group: "Designer — General", desc: "Empty-state text in the Layers panel when the current side has no elements." },
  'designer.layers_locked': { default: "locked", group: "Designer — General", desc: "Badge on the Names & Numbers layer row indicating it is app-positioned and locked." },
  'designer.layers_forward': { default: "Bring forward", group: "Designer — General", desc: "Tooltip on the button that moves a layer one step toward the front." },
  'designer.layers_backward': { default: "Send backward", group: "Designer — General", desc: "Tooltip on the button that moves a layer one step toward the back." },
  'designer.layers_delete': { default: "Delete", group: "Designer — General", desc: "Tooltip on the button that deletes a layer." },
  'designer.rail_products': { default: "Products", group: "Designer — General", desc: "Tool-rail label for the Products (switch garment) item." },
  'designer.rail_text': { default: "Text", group: "Designer — General", desc: "Tool-rail label for the Text tool." },
  'designer.rail_upload': { default: "Upload", group: "Designer — General", desc: "Tool-rail label for the Upload tool." },
  'designer.rail_clipart': { default: "Art", group: "Designer — General", desc: "Tool-rail label for the Art (clipart) tool." },
  'designer.rail_names': { default: "Names & Numbers", group: "Designer — General", desc: "Tool-rail label for the Names & Numbers tool." },
  'designer.rail_layers': { default: "Layers", group: "Designer — General", desc: "Tool-rail label for the Layers tool." },
  'designer.rail_coming_soon': { default: "coming soon", group: "Designer — General", desc: "Suffix in the tooltip of a disabled tool-rail item (e.g. 'Products — coming soon')." },
  'designer.rail_soon': { default: "Soon", group: "Designer — General", desc: "Small badge under a disabled tool-rail item indicating the feature is coming soon." },
  'designer.stepper_aria': { default: "Progress", group: "Designer — General", desc: "Accessibility label for the progress stepper navigation." },
  'designer.stepper_1': { default: "Build It", group: "Designer — General", desc: "Label for step 1 of the progress stepper (designing)." },
  'designer.stepper_2': { default: "Order It", group: "Designer — General", desc: "Label for step 2 of the progress stepper (ordering)." },
  'designer.stepper_3': { default: "Pick Up / Ship", group: "Designer — General", desc: "Label for step 3 of the progress stepper (pickup or shipping at checkout)." },
  'designer.stepper_back': { default: "Back to the designer", group: "Designer — General", desc: "Tooltip on the completed step-1 link that goes back to the designer." },
  'designer.menu_button': { default: "Menu", group: "Designer — General", desc: "Accessible label for the hamburger menu button in the mobile top bar." },
  'designer.my_designs': { default: "My Designs", group: "Designer — General", desc: "Label for the button that opens the customer's saved designs drawer (a count in parentheses may follow)." },
  'designer.price_each': { default: "each", group: "Designer — General", desc: "The word shown after the per-item price in the top bar, as in \"$24.00 each\"." },
  'designer.next_step': { default: "Next Step →", group: "Designer — General", desc: "The primary button that advances the customer from designing to the order step." },
  'designer.your_design_fallback': { default: "Your design", group: "Designer — General", desc: "Fallback title shown in the mobile menu when no product title is available." },
  'designer.canvas.shirt_alt': { default: "Shirt preview", group: "Designer — General", desc: "Alternative text for the garment mockup image behind the design canvas." },
  'designer.empty.build_heading': { default: "Let's build it.", group: "Designer — General", desc: "Greeting headline shown on a blank shirt inviting the customer to start designing." },
  'designer.empty.sub_with_upload': { default: "Add text, upload your art, or browse designs to get started.", group: "Designer — General", desc: "Sub-instruction under the blank-shirt greeting when uploads are available." },
  'designer.empty.sub_no_upload': { default: "Add text or browse designs to get started.", group: "Designer — General", desc: "Sub-instruction under the blank-shirt greeting when uploads are not available (e.g. embroidery)." },
  'designer.empty.add_text': { default: "Add Text", group: "Designer — General", desc: "Button on the blank shirt that starts adding a line of text." },
  'designer.empty.upload': { default: "Upload", group: "Designer — General", desc: "Button on the blank shirt that opens the artwork upload flow." },
  'designer.empty.add_art': { default: "Add Art", group: "Designer — General", desc: "Button on the blank shirt that opens the art/clipart browser." },
  'designer.empty.names': { default: "Names & Numbers", group: "Designer — General", desc: "Button on the blank shirt that opens the Names & Numbers (roster/jersey) tool." },
  'designer.empty.login_tip': { default: 'Designing as a guest — your work stays for this visit. Log in to save it to your account and pick it back up next time.', group: "Designer — General", desc: "Tip in the blank-shirt box telling guests to log in so their design is saved to their account (hidden once logged in — BETA #25)." },
  'designer.product_picker.title': { default: "Use on another product", group: "Designer — General", desc: "Header title of the modal for re-fitting a saved design onto a different garment." },
  'designer.close': { default: "Close", group: "Designer — General", desc: "Accessible label for the X button that closes the product-picker modal." },
  'designer.product_picker.loading': { default: "Loading…", group: "Designer — General", desc: "Placeholder shown while the list of available products is loading." },
  'designer.product_picker.empty': { default: "No other products available.", group: "Designer — General", desc: "Message shown when there are no other garments to re-fit the design onto." },
  'designer.product_picker.refit_hint': { default: "Your design re-fits onto the new garment automatically — a starting point you can nudge.", group: "Designer — General", desc: "Help text at the bottom of the product picker explaining the auto re-fit behavior." },
  'designer.auth.saving': { default: "Saving…", group: "Designer — General", desc: "Login button text shown while the in-progress design is being snapshotted before redirecting to login." },
  'designer.auth.log_in': { default: "Log in", group: "Designer — General", desc: "Button that starts the customer login flow." },
  'designer.auth.name_fallback': { default: "there", group: "Designer — General", desc: "Fallback name used in the greeting (\"Hi, there\") when the customer's name and email are unavailable." },
  'designer.auth.greeting': { default: "Hi,", group: "Designer — General", desc: "Greeting prefix shown before the logged-in customer's name in the top bar." },
  'designer.auth.log_out': { default: "Log out", group: "Designer — General", desc: "Menu item that logs the customer out." },
  'designer.save.saving': { default: "Saving…", group: "Designer — General", desc: "Save button text while a save is in progress." },
  'designer.save.try_again': { default: "Try again", group: "Designer — General", desc: "Save button text shown after a save fails." },
  'designer.save.saved': { default: "Saved ✓", group: "Designer — General", desc: "Save button text shown after a successful save, until the design is edited again." },
  'designer.save.save_changes': { default: "Save changes", group: "Designer — General", desc: "Save button text shown when there are unsaved edits after a prior save." },
  'designer.save.save_design': { default: "Save design", group: "Designer — General", desc: "Default save button text before the design has been saved." },
  'designer.save.design_saved': { default: "Design saved", group: "Designer — General", desc: "Heading of the popover shown after a logged-out customer saves, giving them a shareable link." },
  'designer.dismiss': { default: "Dismiss", group: "Designer — General", desc: "Accessible label for the X button that dismisses the saved-design link popover." },
  'designer.save.link_hint': { default: "Keep this link to come back to your design later:", group: "Designer — General", desc: "Instruction above the shareable restore link in the save popover." },
  'designer.save.copied': { default: "Copied", group: "Designer — General", desc: "Confirmation shown briefly on the copy button after the restore link is copied." },
  'designer.save.copy': { default: "Copy", group: "Designer — General", desc: "Button that copies the restore link to the clipboard." },
  'designer.save.login_prefix': { default: "Or", group: "Designer — General", desc: "First word of the save popover's nudge to log in (\"Or log in and we'll keep it...\")." },
  'designer.save.login_word': { default: "log in", group: "Designer — General", desc: "The emphasized \"log in\" words in the middle of the save popover's login nudge." },
  'designer.save.login_suffix': { default: "and we’ll keep it in your account — no link to hang on to.", group: "Designer — General", desc: "Remainder of the save popover's nudge encouraging the customer to log in instead of keeping a link." },
  'designer.switch_failed': { default: "Couldn't switch products just now — please try again.", group: "Designer — General", desc: "Alert shown when switching the current design to another garment fails to save." },
  'designer.save_empty': { default: "Please add a design before saving. Add text, clipart, or upload an image.", group: "Designer — General", desc: "Alert shown when Save Design is clicked but the canvas is empty." },
  'designer.next_empty': { default: "Please add a design before continuing. Add text, clipart, or upload an image.", group: "Designer — General", desc: "Alert shown when Next Step is clicked but neither side has any design content." },
  'designer.nn_empty_roster': { default: "Your Names & Numbers list has no {fields} filled in yet. Add at least one in the Names & Numbers panel before continuing.", group: "Designer — General", desc: "Blocks Next Step when Names & Numbers placeholders are on the shirt but their roster columns are empty ({fields} = the missing field name(s), e.g. \"name and number\")." },
  'designer.nn_field_name': { default: "name", group: "Designer — General", desc: "The Names & Numbers 'name' field, lowercase, as it appears inside the empty-roster warning." },
  'designer.nn_field_number': { default: "number", group: "Designer — General", desc: "The Names & Numbers 'number' field, lowercase, as it appears inside the empty-roster warning." },
  'designer.nn_field_title': { default: "title", group: "Designer — General", desc: "The Names & Numbers 'title' field, lowercase, as it appears inside the empty-roster warning." },
  'designer.and': { default: "and", group: "Designer — General", desc: "The conjunction joining the last two items in a list (e.g. \"name, number and title\")." },
  'designer.saving': { default: "Saving...", group: "Designer — General", desc: "Temporary label on the Next Step button while the design is being saved." },
  'designer.save_error': { default: "Error saving design. Please try again.", group: "Designer — General", desc: "Alert shown when saving the design before the order step fails." },
  'designer.layer_text': { default: "Text", group: "Designer — General", desc: "Layers panel fallback label for a text layer that has no typed content." },
  'designer.layer_upload': { default: "Upload", group: "Designer — General", desc: "Layers panel fallback label for an uploaded image layer with no filename." },
  'designer.layer_art': { default: "Art", group: "Designer — General", desc: "Layers panel fallback label for a clipart/art layer." },
  'designer.layer_image': { default: "Image", group: "Designer — General", desc: "Layers panel fallback label for a generic image layer." },
  'designer.layer_names_numbers': { default: "Names & Numbers", group: "Designer — General", desc: "Layers panel label for the collapsed Names & Numbers placeholder row." },
  'designer.loading_canvas': { default: "Loading canvas...", group: "Designer — General", desc: "Overlay text shown while the design canvas is initializing." },
  'designer.reset_zoom': { default: "Reset zoom", group: "Designer — General", desc: "Button (mobile) shown while pinch-zoomed in, to return the shirt to normal size." },
  'designer.undo': { default: "Undo", group: "Designer — General", desc: "Tooltip for the mobile Undo (image edit) button." },
  'designer.redo': { default: "Redo", group: "Designer — General", desc: "Tooltip for the mobile Redo (image edit) button." },
  'designer.clear_all_mobile': { default: "Clear all", group: "Designer — General", desc: "Mobile button that clears every object from the canvas." },
  'designer.undo_image_edit': { default: "Undo image edit", group: "Designer — General", desc: "Tooltip for the desktop Undo image-edit button." },
  'designer.redo_image_edit': { default: "Redo image edit", group: "Designer — General", desc: "Tooltip for the desktop Redo image-edit button." },
  'designer.align_label': { default: "Align:", group: "Designer — General", desc: "Label before the object-alignment buttons in the desktop stage toolbar." },
  'designer.zoom_in': { default: "Zoom in", group: "Designer — General", desc: "Tooltip for the magnify-in (+) button in the desktop stage toolbar." },
  'designer.zoom_out': { default: "Zoom out", group: "Designer — General", desc: "Tooltip for the magnify-out (−) button in the desktop stage toolbar." },
  'designer.zoom_reset': { default: "Reset zoom to 100%", group: "Designer — General", desc: "Tooltip for the zoom-percentage button that resets the canvas zoom to 100%." },
  'designer.align_left': { default: "Align Left", group: "Designer — General", desc: "Tooltip for the Align Left object-alignment button." },
  'designer.align_center': { default: "Align Center", group: "Designer — General", desc: "Tooltip for the Align Center object-alignment button." },
  'designer.align_right': { default: "Align Right", group: "Designer — General", desc: "Tooltip for the Align Right object-alignment button." },
  'designer.align_top': { default: "Align Top", group: "Designer — General", desc: "Tooltip for the Align Top object-alignment button." },
  'designer.align_middle': { default: "Align Middle", group: "Designer — General", desc: "Tooltip for the Align Middle object-alignment button." },
  'designer.align_bottom': { default: "Align Bottom", group: "Designer — General", desc: "Tooltip for the Align Bottom object-alignment button." },
  'designer.clear_all_title': { default: "Clear all objects from canvas", group: "Designer — General", desc: "Tooltip for the desktop Clear All button." },
  'designer.clear_all': { default: "Clear All", group: "Designer — General", desc: "Desktop button that clears every object from the canvas." },
  'designer.working': { default: "Working…", group: "Designer — General", desc: "Spinner label shown during background image operations (remove background, uploads, edits)." },
  'designer.front': { default: "FRONT", group: "Designer — General", desc: "Toggle button showing the front of the shirt." },
  'designer.copy_to_back': { default: "Copy to Back", group: "Designer — General", desc: "Button that copies the front design onto the back of the shirt." },
  'designer.copy_to_front': { default: "Copy to Front", group: "Designer — General", desc: "Button that copies the back design onto the front of the shirt." },
  'designer.back': { default: "BACK", group: "Designer — General", desc: "Toggle button showing the back of the shirt." },
  'designer.product_heading': { default: "PRODUCT", group: "Designer — General", desc: "Heading of the right-hand product/color panel." },
  'designer.product_label': { default: "Product", group: "Designer — General", desc: "Row label for the product name in the product panel." },
  'designer.color_label': { default: "Color", group: "Designer — General", desc: "Row label for the selected color in the product panel." },
  'designer.switch_subtitle': { default: "Switch this design to another garment — it re-fits onto:", group: "Designer — General", desc: "Subtitle in the product picker when switching the current design to a different garment." },

  // ── Designer — Upload ──
  'designer.upload.artwork_label': { default: "Upload Artwork", group: "Designer — Upload", desc: "Label above the file-upload dropzone." },
  'designer.upload.drop_here': { default: "Drop image here", group: "Designer — Upload", desc: "Primary prompt inside the upload dropzone." },
  'designer.upload.formats': { default: "JPG · PNG · SVG · AI · PSD · PDF", group: "Designer — Upload", desc: "List of accepted upload file formats shown under the dropzone prompt." },
  'designer.upload.edit_image_label': { default: "Edit Image", group: "Designer — Upload", desc: "Label above the image-editing tools shown for a selected uploaded image." },
  'designer.upload.crop_instructions': { default: "Drag the box on the shirt to frame what to keep, then Apply.", group: "Designer — Upload", desc: "Instructions shown while cropping an uploaded image." },
  'designer.upload.apply_crop': { default: "Apply Crop", group: "Designer — Upload", desc: "Button that commits the crop selection." },
  'designer.upload.cancel': { default: "Cancel", group: "Designer — Upload", desc: "Button that cancels the current crop or color-removal action." },
  'designer.upload.color_removal_instructions': { default: "Adjust until only the color you want is gone, then Apply.", group: "Designer — Upload", desc: "Instructions shown while removing a color from an uploaded image." },
  'designer.upload.color_match_label': { default: "Color match", group: "Designer — Upload", desc: "Label for the tolerance slider that controls how closely colors must match to be removed." },
  'designer.upload.apply': { default: "Apply", group: "Designer — Upload", desc: "Button that commits the color-removal on the image." },
  'designer.upload.remove_background': { default: "Remove Background", group: "Designer — Upload", desc: "Button that automatically removes the background from an uploaded image." },
  'designer.upload.remove_white': { default: "Remove White", group: "Designer — Upload", desc: "Button that removes white pixels from an uploaded image in one tap." },
  'designer.upload.eyedropper_active_mobile': { default: 'Tap the color…', group: 'Designer — Upload', desc: 'Mobile prompt while the eyedropper is armed (touch: "Tap"). Desktop has its own "Click…" version.' },
  'designer.upload.eyedropper_active': { default: "Click the color on the shirt…", group: "Designer — Upload", desc: "Button label while the color-removal eyedropper is armed and waiting for a click on the shirt." },
  'designer.upload.remove_color': { default: "Remove a Color", group: "Designer — Upload", desc: "Button that arms the eyedropper to remove a specific color from an uploaded image." },
  'designer.upload.crop': { default: "Crop…", group: "Designer — Upload", desc: "Button that starts manual cropping of an uploaded image." },
  'designer.upload.processing': { default: "Processing…", group: "Designer — Upload", desc: "Status shown while an image-editing operation is running." },
  'designer.upload.cancel_crop': { default: "Cancel", group: "Designer — Upload", desc: "Button that cancels cropping an uploaded image on mobile." },
  'designer.upload.tolerance_aria': { default: "Color match tolerance", group: "Designer — Upload", desc: "Accessibility label for the color-removal tolerance slider." },
  'designer.upload.apply_color': { default: "Apply", group: "Designer — Upload", desc: "Button that applies removing the picked color from an uploaded image." },
  'designer.upload.cancel_color': { default: "Cancel", group: "Designer — Upload", desc: "Button that cancels the remove-a-color operation on an uploaded image." },
  'designer.upload.upload_image': { default: "Upload image", group: "Designer — Upload", desc: "Label on the mobile upload button/dropzone for adding an image." },
  'designer.upload.loading': { default: "Loading…", group: "Designer — Upload", desc: "Shown while the customer's My Uploads library is loading." },
  'designer.upload.empty_mobile': { default: "No uploads yet — add one above.", group: "Designer — Upload", desc: "Empty-state message in the mobile My Uploads strip when the customer has no uploads." },
  'designer.upload.tile_add': { default: "Add", group: "Designer — Upload", desc: "The verb prefix in the tooltip on an uploaded-image tile (followed by the file name), e.g. Add \"logo.png\"." },
  'designer.upload.tile_add_suffix': { default: "to your design", group: "Designer — Upload", desc: "The trailing phrase in the desktop upload-tile tooltip, e.g. Add \"logo.png\" to your design." },
  'designer.upload.remove_tooltip': { default: "Remove from My Uploads", group: "Designer — Upload", desc: "Tooltip on the small ✕ button that removes an image from the My Uploads library." },
  'designer.upload.heading': { default: "My Uploads", group: "Designer — Upload", desc: "Section heading above the customer's uploaded-image library in the designer." },
  'designer.upload.empty_title': { default: "No uploads yet", group: "Designer — Upload", desc: "Empty-state title in the desktop My Uploads panel when there are no uploads." },
  'designer.upload.empty_hint': { default: "Images you upload appear here to reuse on any design.", group: "Designer — Upload", desc: "Empty-state helper text explaining that uploaded images are reusable across designs." },
  'designer.upload.add_overlay': { default: "+ Add", group: "Designer — Upload", desc: "Label that appears over an upload tile on hover, indicating clicking adds it to the design." },
  'designer.upload_add_failed': { default: "Could not add that image. Please try again.", group: "Designer — Upload", desc: "Alert shown when re-adding a saved upload from the library to the shirt fails." },
  'designer.pdf_load_failed': { default: "Could not load PDF. Make sure it is a valid PDF file.", group: "Designer — Upload", desc: "Alert shown when an uploaded PDF cannot be opened/rasterized." },
  'designer.image_edit_failed': { default: "We couldn't edit this image — it may be blocked by the source server. Try re-uploading it, then edit.", group: "Designer — Upload", desc: "Alert shown when an image edit (crop/remove-color/etc.) cannot read the image pixels." },
  'designer.image_read_failed': { default: "We couldn't read this image (it may be blocked by the source server). Try re-uploading it.", group: "Designer — Upload", desc: "Alert shown when Remove White or the color eyedropper cannot read the selected image's pixels." },
  'designer.removebg_wait': { default: "Please wait a moment for the upload to finish (or re-upload the image), then try Remove Background again.", group: "Designer — Upload", desc: "Alert shown when Remove Background is used before the image finished uploading." },
  'designer.removebg_no_image': { default: "Background removal returned no image.", group: "Designer — Upload", desc: "Alert shown when the Remove Background service returns no resulting image." },
  'designer.removebg_unexpected': { default: "Background removal returned an unexpected response.", group: "Designer — Upload", desc: "Alert prefix shown when the Remove Background service returns an unexpected (non-image) response." },

  // ── Designer — Art ──
  'designer.art.color_label': { default: "Clipart Color", group: "Designer — Art", desc: "Label above the recolor swatches for a selected SVG clipart." },
  'designer.art.color_default_name': { default: "Black", group: "Designer — Art", desc: "Fallback name shown for the chosen clipart color when it doesn't match a named palette color." },
  'designer.art.search_placeholder': { default: "Search art or Design #...", group: "Designer — Art", desc: "Placeholder text in the art browser's search box where customers type an art name or design number." },
  'designer.art.loading': { default: "Loading...", group: "Designer — Art", desc: "Shown while the art library is loading in the designer's Art panel." },
  'designer.art.empty': { default: "No art found", group: "Designer — Art", desc: "Shown in the Art panel when no artwork matches the current category or search." },

  // ── Designer — Names & Numbers ──
  'nn.heading': { default: "Names & Numbers", group: "Designer — Names & Numbers", desc: "Heading of the Names & Numbers roster panel." },
  'nn.intro_a': { default: "Name, Number, and Title are", group: "Designer — Names & Numbers", desc: "First part of the intro line explaining the placeholder fields." },
  'nn.intro_placeholders': { default: "placeholders", group: "Designer — Names & Numbers", desc: "The emphasized word 'placeholders' inside the intro line." },
  'nn.intro_b': { default: "— style each once (font, color, size). Every row in your list prints as its own shirt. Text prints UPPERCASE.", group: "Designer — Names & Numbers", desc: "Rest of the intro line describing how styling and per-row printing works." },
  'nn.name_done': { default: "Name ✓", group: "Designer — Names & Numbers", desc: "Label on the Add-Name button once a Name field has been placed on the shirt." },
  'nn.add_name': { default: "Add Name", group: "Designer — Names & Numbers", desc: "Button that adds a Name placeholder field to the shirt." },
  'nn.number_done': { default: "Number ✓", group: "Designer — Names & Numbers", desc: "Label on the Add-Number button once a Number field has been placed on the shirt." },
  'nn.add_number': { default: "Add Number", group: "Designer — Names & Numbers", desc: "Button that adds a Number placeholder field to the shirt." },
  'nn.title_done': { default: "Title ✓", group: "Designer — Names & Numbers", desc: "Label on the Add-Title button once a Title field has been placed on the shirt." },
  'nn.add_title': { default: "Add Title", group: "Designer — Names & Numbers", desc: "Button that adds a Title placeholder field to the shirt." },
  'nn.no_print_area_a': { default: "This product doesn't have a print area loaded yet, so there's nowhere to place the name/number. Add a print area for it in", group: "Designer — Names & Numbers", desc: "Warning shown when the product has no print area for placing name/number (first part)." },
  'nn.no_print_area_templates': { default: "Templates", group: "Designer — Names & Numbers", desc: "The word 'Templates' (admin area name) inside the no-print-area warning." },
  'nn.no_print_area_b': { default: "(admin), then reload the designer.", group: "Designer — Names & Numbers", desc: "End of the no-print-area warning telling the user to reload the designer." },
  'nn.col_name': { default: "Name", group: "Designer — Names & Numbers", desc: "Column header for the Name field in the roster table." },
  'nn.col_number': { default: "Number", group: "Designer — Names & Numbers", desc: "Column header for the Number field in the roster table." },
  'nn.col_title': { default: "Title", group: "Designer — Names & Numbers", desc: "Column header for the Title field in the roster table." },
  'nn.col_size': { default: "Size", group: "Designer — Names & Numbers", desc: "Column header for the Size field in the roster table." },
  'nn.col_qty': { default: "Qty", group: "Designer — Names & Numbers", desc: "Column header for the Quantity field in the roster table." },
  'nn.ph_name': { default: "SMITH", group: "Designer — Names & Numbers", desc: "Example placeholder text in the roster Name input." },
  'nn.ph_number': { default: "12", group: "Designer — Names & Numbers", desc: "Example placeholder text in the roster Number input." },
  'nn.ph_title': { default: "CAPTAIN", group: "Designer — Names & Numbers", desc: "Example placeholder text in the roster Title input." },
  'nn.ph_size': { default: "L", group: "Designer — Names & Numbers", desc: "Example placeholder text in the roster Size input (used when there is no size dropdown)." },
  'nn.row_remove': { default: "Remove", group: "Designer — Names & Numbers", desc: "Tooltip on the button that removes a roster row." },
  'nn.add_row': { default: "Add row", group: "Designer — Names & Numbers", desc: "Button that adds a new blank row to the roster." },
  'nn.shirt_one': { default: "shirt", group: "Designer — Names & Numbers", desc: "Singular unit word shown after the shirt count (e.g. '1 shirt')." },
  'nn.shirt_many': { default: "shirts", group: "Designer — Names & Numbers", desc: "Plural unit word shown after the shirt count (e.g. '3 shirts')." },
  'nn.preview_start': { default: "Preview on shirt", group: "Designer — Names & Numbers", desc: "Button that starts cycling the roster entries onto the shirt as a live preview." },
  'nn.preview_prev': { default: "Previous", group: "Designer — Names & Numbers", desc: "Tooltip on the previous-entry arrow in the roster preview." },
  'nn.preview_next': { default: "Next", group: "Designer — Names & Numbers", desc: "Tooltip on the next-entry arrow in the roster preview." },
  'nn.preview_exit': { default: "Exit preview", group: "Designer — Names & Numbers", desc: "Tooltip on the button that exits the roster preview." },
  'nn.preview_done': { default: "Done", group: "Designer — Names & Numbers", desc: "Label on the button that ends the roster preview." },
  'nn.role_name': { default: "Name", group: "Designer — Names & Numbers", desc: "Field name used in the 'Style the ... field' styling header when a Name placeholder is selected." },
  'nn.role_title': { default: "Title", group: "Designer — Names & Numbers", desc: "Field name used in the 'Style the ... field' styling header when a Title placeholder is selected." },
  'nn.role_number': { default: "Number", group: "Designer — Names & Numbers", desc: "Field name used in the 'Style the ... field' styling header when a Number placeholder is selected." },
  'nn.sample_name': { default: "NAME", group: "Designer — Names & Numbers", desc: "Sample word previewed in each font in the picker when styling a Name field." },
  'nn.sample_title': { default: "TITLE", group: "Designer — Names & Numbers", desc: "Sample word previewed in each font in the picker when styling a Title field." },
  'nn.sample_number': { default: "00", group: "Designer — Names & Numbers", desc: "Sample digits previewed in each font in the picker when styling a Number field." },
  'nn.style_the': { default: "Style the", group: "Designer — Names & Numbers", desc: "First part of the selected-placeholder styling header ('Style the <field> field')." },
  'nn.style_field': { default: "field", group: "Designer — Names & Numbers", desc: "The word 'field' at the end of the selected-placeholder styling header." },
  'nn.style_done': { default: "Done", group: "Designer — Names & Numbers", desc: "Link that closes the selected-placeholder styling panel." },
  'nn.font_label': { default: "Font", group: "Designer — Names & Numbers", desc: "Label above the font picker in the placeholder styling panel." },
  'nn.color_label': { default: "Color", group: "Designer — Names & Numbers", desc: "Label above the ink color swatches in the placeholder styling panel." },
  'nn.color_hint': { default: "— one ink, all fields", group: "Designer — Names & Numbers", desc: "Hint next to the Color label noting a single ink color applies to all fields." },
  'nn.style_note_a': { default: "Font & color only — position and size are set automatically to the jersey layout (long names shrink to fit). Every", group: "Designer — Names & Numbers", desc: "Explanatory note under the styling controls (first part, before the field role word)." },
  'nn.style_note_b': { default: "on your roster prints this way.", group: "Designer — Names & Numbers", desc: "End of the styling explanatory note (after the field role word)." },
  'nn.paste_prompt': { default: "Have a spreadsheet?", group: "Designer — Names & Numbers", desc: "Prompt inviting the customer to paste a roster from a spreadsheet." },
  'nn.paste_link': { default: "Paste a list", group: "Designer — Names & Numbers", desc: "Link that opens the bulk paste-a-roster box." },
  'nn.template_link': { default: "Template", group: "Designer — Names & Numbers", desc: "Link to download the blank roster spreadsheet template." },
  'nn.paste_format_a': { default: "One shirt per line:", group: "Designer — Names & Numbers", desc: "Start of the paste-format guidance line." },
  'nn.paste_format_cols': { default: "Name, Number, Size, Qty, Title", group: "Designer — Names & Numbers", desc: "The column order shown in the paste-format guidance." },
  'nn.paste_format_b': { default: "— Title is optional, e.g.", group: "Designer — Names & Numbers", desc: "Middle of the paste-format guidance noting Title is optional, before the example." },
  'nn.paste_format_example': { default: "SMITH, 12, L, 1, CAPTAIN", group: "Designer — Names & Numbers", desc: "Example roster line in the paste-format guidance." },
  'nn.paste_placeholder': { default: "SMITH, 12, L, 1, CAPTAIN\nJONES, 8, M, 1\nDE LA CRUZ, 24, XL, 2", group: "Designer — Names & Numbers", desc: "Multi-line placeholder text inside the bulk paste-a-roster textarea." },
  'nn.paste_apply': { default: "Apply list", group: "Designer — Names & Numbers", desc: "Button that applies the pasted roster list." },
  'nn.paste_cancel': { default: "Cancel", group: "Designer — Names & Numbers", desc: "Button that cancels the bulk paste-a-roster box." },
  'nn.paste_note': { default: "Tab or comma separated (a spreadsheet copy works). Replaces the current list.", group: "Designer — Names & Numbers", desc: "Note under the paste box explaining accepted formats and that it replaces the current list." },

  // ── Order page ──
  'order.error_not_found': { default: "Design not found", group: "Order page", desc: "Error shown when the design for this order link cannot be loaded." },
  'order.error_select_size': { default: "Please select at least one size and quantity.", group: "Order page", desc: "Validation message when the customer tries to add to cart without choosing any quantities." },
  'order.error_add_failed': { default: "Could not add to cart — please try again.", group: "Order page", desc: "Fallback error shown when adding the design to the cart fails." },
  'order.already_in_cart_confirm': { default: "This design is already in your cart. Select OK to view your cart, or Cancel to add another copy.", group: "Order page", desc: "Confirm shown when the customer re-adds a design already in their cart — OK goes to the cart, Cancel adds a second copy." },
  'order.loading': { default: "Loading your design...", group: "Order page", desc: "Loading message while the order page fetches the saved design." },
  'order.your_design': { default: "Your Design", group: "Order page", desc: "Heading above the design preview on the order page." },
  'order.no_preview': { default: "No preview available", group: "Order page", desc: "Placeholder shown when no design preview image is available." },
  'order.side_front': { default: "FRONT", group: "Order page", desc: "Label above the front-side design preview image." },
  'order.side_back': { default: "BACK", group: "Order page", desc: "Label above the back-side design preview image." },
  'order.side_blank': { default: "No design on this side (blank)", group: "Order page", desc: "Shown on the preview when the product has this side but the customer left it blank." },
  'order.edit_design': { default: "← Edit Design", group: "Order page", desc: "Link that takes the customer back to the designer to edit their design." },
  'order.product_label': { default: "Product", group: "Order page", desc: "Small label above the product name in the order summary." },
  'order.color_label': { default: "Color:", group: "Order page", desc: "Prefix label before the selected garment color." },
  'order.method_label': { default: "Method:", group: "Order page", desc: "Prefix label before the print method in the order summary." },
  'order.method_print': { default: "Print", group: "Order page", desc: "Displayed name for the standard print method on the order summary." },
  'order.pricing_label': { default: "Pricing", group: "Order page", desc: "Section header for the price breakdown." },
  'order.front_print': { default: "Front Print", group: "Order page", desc: "Line-item label for the front-side print charge in the price breakdown." },
  'order.back_print': { default: "Back Print", group: "Order page", desc: "Line-item label for the back-side print charge in the price breakdown." },
  'order.nn_personalization': { default: "Personalization (names & numbers)", group: "Order page", desc: "Price-breakdown label for names & numbers personalization." },
  'order.nn_included': { default: "included in print", group: "Order page", desc: "Note that personalization is already included in the print charge (no extra cost)." },
  'order.price_per_item': { default: "Price per item", group: "Order page", desc: "Label for the per-shirt price total in the price breakdown." },
  'order.nn_heading': { default: "Names & Numbers", group: "Order page", desc: "Section header shown for a names & numbers roster order." },
  'order.sizes_heading': { default: "Sizes & Quantities", group: "Order page", desc: "Section header for the size/quantity chooser." },
  'order.roster_name': { default: "Name", group: "Order page", desc: "Column header for the name in the names & numbers roster manifest." },
  'order.roster_number': { default: "Number", group: "Order page", desc: "Column header for the number in the names & numbers roster manifest." },
  'order.roster_title': { default: "Title", group: "Order page", desc: "Column header for the optional title in the names & numbers roster manifest." },
  'order.roster_size': { default: "Size", group: "Order page", desc: "Column header for the shirt size in the names & numbers roster manifest." },
  'order.roster_qty': { default: "Qty", group: "Order page", desc: "Column header for the quantity in the names & numbers roster manifest." },
  'order.roster_hint': { default: "Edit this list in the designer — it sets the shirts and quantities.", group: "Order page", desc: "Helper note telling the customer the roster is edited back in the designer." },
  'order.total_quantity': { default: "Total quantity", group: "Order page", desc: "Label for the total number of shirts in the order totals." },
  'order.order_total': { default: "Order total", group: "Order page", desc: "Label for the order grand total." },
  'order.volume_savings': { default: "Volume savings", group: "Order page", desc: "Header for the volume-discount incentive section." },
  'order.volume_tier_save': { default: "save", group: "Order page", desc: "Word between the quantity threshold and percent in a volume-savings tier chip (e.g. '20+ save 10%')." },
  'order.volume_add': { default: "Add", group: "Order page", desc: "Opening word of the 'add N more to save X%' volume nudge." },
  'order.volume_more_to_save': { default: "more to save", group: "Order page", desc: "Middle phrase of the 'add N more to save X% on your order' volume nudge." },
  'order.volume_on_order': { default: "on your order.", group: "Order page", desc: "Closing phrase of the 'add N more to save X% on your order' volume nudge." },
  'order.volume_youre_getting': { default: "You’re getting", group: "Order page", desc: "Opening phrase of the top-tier volume-discount confirmation." },
  'order.volume_pct_off': { default: "% off", group: "Order page", desc: "Suffix after the discount percent in the top-tier confirmation (e.g. '10% off')." },
  'order.volume_top_tier': { default: "— the top tier. 🎉", group: "Order page", desc: "Closing phrase telling the customer they reached the highest volume-discount tier." },
  'order.volume_auto_checkout': { default: "Discount applied automatically in your cart.", group: "Order page", desc: "Note that the volume discount is applied automatically in the cart." },
  'order.subtotal_before_discount': { default: "Subtotal (before discount)", group: "Order page", desc: "Label replacing 'Order total' when a volume discount applies — the pre-discount figure, de-emphasized." },
  'order.nn_bad_sizes': { default: "Some roster rows use a size this product doesn't offer ({sizes}). Go back to Edit Design to fix those sizes before checkout.", group: "Order page", desc: "Warning when a Names & Numbers roster has sizes the product doesn't offer ({sizes} = the mismatched size list)." },
  'order.volume_discount_line': { default: "Volume discount", group: "Order page", desc: "Label on the estimated volume-discount amount line (shown as −$X)." },
  'order.volume_estimated_total': { default: "Estimated total", group: "Order page", desc: "Label on the estimated order total after the volume discount." },
  'order.notes_label': { default: "Design Notes", group: "Order page", desc: "Label for the optional design-notes text area." },
  'order.notes_optional': { default: "(optional)", group: "Order page", desc: "'(optional)' qualifier next to the Design Notes label." },
  'order.notes_placeholder': { default: "Printing details for our team — e.g. exact ink color, placement notes…", group: "Order page", desc: "Placeholder text inside the design-notes text area." },
  'order.adding_to_cart': { default: "Adding to Cart...", group: "Order page", desc: "Add-to-cart button label while the request is in progress." },
  'order.add_to_cart': { default: "Add to Cart →", group: "Order page", desc: "Primary add-to-cart button label (an item count is appended after it)." },
  'order.keep_shopping': { default: "Keep shopping or check out from your cart when you're ready", group: "Order page", desc: "Reassurance note below the add-to-cart button that the customer can keep shopping." },
  // ── Notifications / errors (interpolated — {placeholders} are filled in at runtime) ──
  'notify.method_switch_confirm': { default: 'Switching to {method} will {actions}. Continue?', group: 'Notifications', desc: 'Confirmation before a print-method switch that changes the design ({method} = Print/Embroidery, {actions} = what will change).' },
  'notify.switch_remove_uploads': { default: 'uploaded images', group: 'Notifications', desc: 'Phrase for uploaded images inside the method-switch confirmation.' },
  'notify.switch_remove_art': { default: "art that isn't available for {method}", group: 'Notifications', desc: "Phrase for art that won't carry to the new method, inside the method-switch confirmation." },
  'notify.switch_remove_prefix': { default: 'remove your {items}', group: 'Notifications', desc: 'Wraps the list of things removed on a method switch (e.g. "remove your uploaded images").' },
  'notify.switch_restyle_text': { default: 'set your text to an embroidery font + thread color', group: 'Notifications', desc: 'Phrase for restyling text when switching to embroidery, in the method-switch confirmation.' },
  'notify.file_too_large': { default: "That file is {size} MB, but the largest we can upload here is {max} MB.\n\nPlease upload a smaller version — or email the original file to us at {email} and we'll add it to your order.", group: 'Notifications', desc: 'Alert when an uploaded file is over the size limit.' },
  'notify.eps_unsupported': { default: "We can't process EPS files here — please email the file to us at {email} and we'll add it to your order.", group: 'Notifications', desc: 'Alert when an EPS file (unsupported) is uploaded.' },
  'notify.convert_failed': { default: "We couldn't process your {ext} file: {error}\n\nPlease try a different file, or email the original to us at {email} and we'll add it to your order.", group: 'Notifications', desc: 'Alert when an AI/PSD file conversion fails.' },
  'notify.pdf_multipage': { default: 'Your PDF has {pages} pages — only page 1 was added to the design. If you need a different page, please upload just that page.', group: 'Notifications', desc: 'Notice when a multi-page PDF is uploaded (only page 1 is used).' },
  'notify.pdf_original_lost': { default: "We added your design, but couldn't save the original PDF at full quality for production. Please email the original to us at {email} and we'll attach it to your order.", group: 'Notifications', desc: 'Notice when the design was added but the original PDF could not be saved.' },
  'notify.pdf_save_failed': { default: "We couldn't save your PDF upload — please try again, or email the file to us at {email}.", group: 'Notifications', desc: 'Notice when a PDF upload fails entirely.' },
  'notify.bg_removal_failed': { default: 'Background removal failed (HTTP {status}).', group: 'Notifications', desc: 'Alert when the background-removal request fails (server detail may be appended).' },
  'notify.bg_removal_error': { default: 'Background removal error: {error}', group: 'Notifications', desc: 'Alert when background removal throws an unexpected error.' },
  // ── Designer — Upload (guidance + low-res warnings) ──
  'upload.guidance': { default: 'Vector or high-resolution artwork (300 DPI or more) will look best. Max size {max} MB.', group: 'Designer — Upload', desc: 'Guidance under the upload dropzone about ideal artwork + the size limit.' },
  'upload.lowres_small': { default: '⚠ This image is low-resolution and may print blurry. For the sharpest print use 300 DPI or higher — or email us your original file.', group: 'Designer — Upload', desc: 'Warning shown when an uploaded image is low-resolution.' },
  'upload.lowres_placed': { default: '⚠ Low resolution at this size — may print blurry. Try making it smaller, use a higher-resolution image, or email us your original.', group: 'Designer — Upload', desc: 'Warning shown when an image is scaled larger than its resolution supports.' },
} as const satisfies Record<string, UiStringDef>

export type UiStringKey = keyof typeof UI_STRINGS

// Resolve a key: admin override ?? inline fallback ?? registry default ?? the key itself. The optional
// `fallback` (the original literal text at the call site) means a string ALWAYS renders correctly even if
// its registry entry hasn't landed yet — so wiring `t('key', 'Original text')` is safe out of order.
export function resolveString(
  key: string, overrides: Record<string, string> | null | undefined, fallback?: string,
): string {
  if (overrides && key in overrides) return overrides[key]
  if (fallback !== undefined) return fallback
  const def = (UI_STRINGS as Record<string, UiStringDef>)[key]
  return def ? def.default : key
}

// Interpolate {name} placeholders in a resolved template — for error/notice wording that embeds live
// values, e.g. format(t('upload.oversize', 'That file is {size} MB, max {max} MB.'), { size: 12, max: 25 }).
// A placeholder with no matching var is left literally as {name} (visible, never blank).
export function format(template: string, vars: Record<string, string | number>): string {
  return template.replace(/\{(\w+)\}/g, (_, k) => (k in vars ? String(vars[k]) : `{${k}}`))
}

// Grouped view of the registry for the admin Language page (stable group order = first-seen).
export function groupedStrings(): { group: string; items: { key: string; def: UiStringDef }[] }[] {
  const order: string[] = []
  const byGroup = new Map<string, { key: string; def: UiStringDef }[]>()
  for (const [key, def] of Object.entries(UI_STRINGS) as [string, UiStringDef][]) {
    if (!byGroup.has(def.group)) { byGroup.set(def.group, []); order.push(def.group) }
    byGroup.get(def.group)!.push({ key, def })
  }
  return order.map(group => ({ group, items: byGroup.get(group)! }))
}
